In [32]:
import pandas as pd

In [33]:
df1 = pd.read_csv('contacts_preprocessed.csv', index_col=0)
df2 = pd.read_csv('searches_preprocessed.csv', index_col=0)

In [34]:
final_df = pd.merge(df1, df2, left_on='id_guest', right_on='id_user')
final_df = final_df.drop('id_user', axis=1)

In [35]:
final_df.to_csv('final_preprocessed.csv')

In [36]:
final_df

,id_guest,id_host,id_listing,ts_contact_at,ts_reply_at,ts_accepted_at,ts_booking_at,ds_checkin,ds_checkout,n_guests,...,ds,n_searches,n_nights,n_guests_min,n_guests_max,origin_country,filter_price_min,filter_price_max,filter_room_types,filter_neighborhoods
0,000dfad9-459b-4f0b-8310-3d6ab34e4f57,13bb24b8-d432-43a2-9755-5ea11b43bb69,21d2b1a2-fdc3-4b4c-a1f0-0eaf0cc02370,2014-10-04 16:26:28.0,2014-10-04 16:26:28.0,2014-10-04 16:26:28.0,2014-10-04 16:26:28.0,2014-10-13,2014-10-15,2.0,...,2014-10-04,6.000000,2.000000,2.00,2.0,CA,0.0,1.300000e+02,",Entire home/apt",NaN
1,00197051-c6cb-4c3a-99e9-86615b819874,46aa3897-9c00-4d76-ac66-a307593d0675,fb5ed09a-9848-4f2c-b2ef-34deb62164fb,2014-11-04 09:10:03.0,2014-11-04 09:45:50.0,2014-11-04 09:45:50.0,2014-11-04 12:20:46.0,2014-11-27,2014-11-30,1.0,...,2014-10-14,13.000000,3.000000,1.00,1.0,DK,0.0,3.360000e+02,",Entire home/apt,Private room,Private room",NaN
2,0027538e-aa9e-4a02-8979-b8397e5d4cba,"ac162061-55e2-4072-ac91-2e080f9581f2, 8772bc85...","0d9b5583-8053-4b67-adfe-8c29eb12efed, ec68e0af...","2014-10-10 15:22:26.0, 2014-10-10 12:02:50.0, ...","2014-10-10 15:24:26.0, 2014-10-10 15:07:01.0",2014-10-10 15:24:26.0,2014-10-10 15:52:42.0,2014-10-17,2014-10-19,2.0,...,"2014-10-09, 2014-10-10",32.500000,2.000000,2.00,2.0,CY,0.0,7.360000e+02,",Entire home/apt, ,Entire home/apt,Entire home...",NaN
3,006b68ec-9374-4061-a954-6ae10f838b9e,"16a2ccae-60a6-445a-9cc4-8f0d83e454f2, 42bae547...","9d8e30e9-dcc9-4148-82f7-39f7297b48f9, f375e1c9...","2014-10-02 00:21:08.0, 2014-10-04 09:15:47.0",2014-10-04 14:42:00.0,NaN,NaN,2014-10-04,2014-10-05,3.0,...,"2014-10-04, 2014-10-02",7.250000,1.000000,1.50,2.0,GB,NaN,NaN,NaN,NaN
4,006c93e2-199f-4b35-a094-4176c43034be,ee55912a-88a0-414d-aed7-7f15ce527232,71bca3ca-cbbf-4496-b35b-15dcc39552da,2014-10-02 04:09:28.0,2014-10-02 06:58:38.0,NaN,NaN,2014-11-05,2014-11-07,2.0,...,2014-10-02,3.000000,2.000000,2.00,2.0,US,0.0,1.010000e+02,Private room,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3278,ffc234be-ca13-4bcb-a472-1c136b800891,"1f98db75-fa8f-4654-a2c2-b70313e7c71b, 6a460cb8...","f56282e3-3575-4547-a206-97b73b128ee1, 53e37de5...","2014-10-08 16:04:17.0, 2014-10-03 11:40:29.0, ...","2014-10-08 15:38:18.0, 2014-10-08 15:38:53.0, ...","2014-10-08 19:31:19.0, 2014-10-09 10:21:33.0, ...",NaN,"2014-10-09, 2014-10-04","2014-10-11, 2014-10-17, 2014-10-12",1.0,...,"2014-10-08, 2014-10-04, 2014-10-09, 2014-10-02",16.000000,7.166667,1.00,1.0,RU,0.0,2.684355e+08,NaN,",City Centre"
3279,ffdf7f20-8d0f-4801-8f73-3b00a1bba4c3,"2a0feb74-d403-4f66-82e7-2087dae9c598, 3d5b814d...","1b375b48-1924-4111-a50e-6538bd39d4ba, 61d37df9...","2014-10-08 13:20:51.0, 2014-10-08 13:49:00.0, ...","2014-10-08 15:36:22.0, 2014-10-09 11:26:31.0, ...","2014-10-08 15:36:22.0, 2014-10-09 11:26:31.0",2014-10-15 22:15:51.0,2014-11-18,2014-11-22,2.0,...,2014-10-08,15.000000,4.000000,2.00,2.0,DE,0.0,1.110000e+02,NaN,NaN
3280,ffe1316f-8628-48ff-9cec-7ae59038a231,9117bd5e-2d56-47c0-a15b-79b61b8c5835,60187530-2ddd-4824-94c1-84dac9b7368c,2014-10-01 15:38:53.0,2014-10-01 15:42:37.0,2014-10-01 21:45:56.0,NaN,2014-11-22,2014-11-23,4.0,...,2014-10-01,3.666667,11.000000,1.00,2.0,IE,0.0,1.280000e+02,",Entire home/apt",NaN
3281,ffe366f0-6ab6-4e94-818a-c69c125fed3c,"76b4e24e-2b33-4acf-b688-3622675a121c, d0b6d89a...","7732bad8-e800-49f3-8751-e7604e3fb5a3, 28caf371...","2014-10-13 15:40:49.0, 2014-10-13 15:38:28.0, ...","2014-10-08 08:19:33.0, 2014-10-13 15:42:46.0, ...","2014-10-13 16:25:41.0, 2014-10-08 08:19:33.0, ...",2014-10-13 21:01:34.0,2014-10-17,2014-10-20,2.0,...,"2014-10-12, 2014-10-07, 2014-10-03, 2014-10-13...",13.800000,3.200000,1.80,2.0,IT,0.0,4.294968e+08,NaN,NaN
3282,fffea166-9432-43a7-8b1b-09d6f30c1c07,6d656267-642e-4972-bdec-a35d82b84ebb,90dddef6-23ef-4df3-b454-8fd3d0e8cade,2014-10-08 00:05:05.0,2014-10-12 20:58:12.0,NaN,NaN,2014-11-11,2014-11-18,2.0,...,"2014-10-08, 2014-10-07, 2014-10-06",3.000000,12.250000,1.75,2.0,AR,0.0,7.933333e+01,NaN,NaN